### ISSUE TITLE
xcolor package missing and readme entry about literate

### ISSUE THREAD

**Issue by sebastianpech** [wg030/jlcode#1]
Hi, thanks for all your work. 
Your missing a `\RequirePackage{xcolor}` in your `sty`.

About your entry in the README.md:

> No Support for Special Unicode Characters Yet

You could add a note about using the `literate` option to display e.g. greek letters.
```
\lstset{
  extendedchars=true,
  literate={α}{{$\alpha$}}1 {β}{{$\beta$}}1
}
```

**Comment by wg030** [comment]
Hi, thanks for writing your comment.

You are right I forgot to put the xcolor package into my sty file, too.
I have created a test file now to make sure it really works.

Concerning the special unicode characters, your suggestion is, of course, a good one.
However one has to be carful with the colors. Doing it the way you suggested it with my language definition α and β would be displayed with the color "jlstring", i.e. it would have the same color as strings have. But in variable names you want them to be coloured with "jlbase", which you could add into your literate definition to achieve that. However in that case all α and β will be displayed in that color, even if they are contained in a comment or a string, which you don't want, of course.
The only solution for that problem that I see right now is to add them to the "alsoletter" attribute of the listings package, but I haven't figured out how to do that corrrectly yet.
Nevertheless it's a good idea to add a comment about that in the README.md.
