### ISSUE TITLE
Width of the frame

### ISSUE THREAD

**Issue by linwaytin** [wg030/jlcode#12]
First, thanks a lot for this package.
Otherwise I don't how to print my code with Greek letters.

I found the width of the frame seems fixed to 80 characters.
I would like to suggest making this changeable, because sometimes long lines exist.

Thank you for this great work!

**Comment by wg030** [comment]
Hey linwaytin,

you are right that I designed the package in such a way that the code box is for 80 characters per line exactly. Personally I think when writing good it's a good style to stick to a fixed number. The number 80 itself comes form the default value used by Atom, the editor, which I work with when programming julia code.


However I hear your wish to change that. For a quick fix, simply change the "80" in line 902 of jlcode.sty to which ever number you prefer.


I will make that a package option in thex next version of the package using 80 as default value, but I don't know when I will have some time to do so.

**Comment by linwaytin** [comment]
Thank you!

**Comment by wg030** [comment]
I have now updated the package and added the option `charsperline`
So from now you can control the characters per line, i.e. the width of the code box, when loading the package. Use for example

`\usepackage[charsperline=90]{jlcode}`
