### ISSUE TITLE
Add $\times$ symbol

### ISSUE THREAD

**Issue by dpo** [wg030/jlcode#13]
I suggest adding
```
{×}{{\ucc{$\times$}}}{1}
```
which is useful when converting a Jupyter notebook to LaTeX to properly display output such as
```julia
1×3 Array{Float64,2}:
 1.0  2.3  3.14
```

**Comment by wg030** [comment]
Great suggestion!
With the latest update I have included the `×` symbol together with a few more further mathematical symbols. However I made them a little smaller, using scriptsize, since they appared too big compared to the normal operators like `+` or `-`.
