### ISSUE TITLE
1e-12 and 1E-12 wrong color

### ISSUE THREAD

**Issue by HFriberg** [wg030/jlcode#2]
Numbers are red, but 'e' is green and 'E' is black in "1e-12 and 1E-12". I would like 'e' and 'E' to be part of the number and as so colored red.

**Comment by HFriberg** [comment]
My best suggestion, given that 'e' is also a constant, is to add under `% julia's numbers` all relevant combinations:
{0e-}{{{\color{jlstring}0e-}}}{3}
{0e+}{{{\color{jlstring}0e+}}}{3}
{0E-}{{{\color{jlstring}0E-}}}{3}
{0E+}{{{\color{jlstring}0E+}}}{3}

and the copies where 0 is replaced by 1,2,3,4,5,6,7,8 and 9.

**Comment by wg030** [comment]
Nice suggestion, thank you!
I have considered it with my latest upadte.

However for the small e literating with
{0e+}{{{\color{jlstring}0e+}}}{3}
did not work correctly, so I had to do it with
{e+0}{{{\color{jlstring}e+0}}}{3}
