### ISSUE TITLE
unicode variables with numbers do not get properly syntaxed

### ISSUE THREAD

**Issue by lmiq** [wg030/jlcode#21]
For example:

`σ6 = σ^6`

appears as

![image](https://user-images.githubusercontent.com/31046348/93786312-8be07300-fc05-11ea-9a6e-aa83f06bd5c9.png)

and not as variable, for example as in `r6 = r2^3`:

![image](https://user-images.githubusercontent.com/31046348/93786387-a4e92400-fc05-11ea-9855-8129afc698f3.png)

(ps: thanks for the great package)

**Comment by wg030** [comment]
> (ps: thanks for the great package)

You are welcome, Imiq!

The problem you described is unfortunately a problem that I don't have a good solution for. However I have implemented a fix already. Please take a close look at section 10 of the manual. This should teach you how to make such expressions look the way that they are supposed to look.
