### ISSUE TITLE
Undefined color `jlbase` (xcolor)

### ISSUE THREAD

**Issue by emsal0** [wg030/jlcode#23]
Put `jlcode.sty` in my local package library, using `\usepackage{jlcode}` in my document.

Get the following error:

```
Error producing PDF.
! Package xcolor Error: Undefined color `jlbase'.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.138   The
```

**Comment by wg030** [comment]
Hmm, I just run my tex file for the manual and can confirm that the error also appears for me now.
Since the tex file worked like a charm a few months ago, something outside the jlcode package seems to have changed that now causes this error. However I haven't found out what is going on yet.
Could you maybe create an minimal working a example that shows under which circumstances this error appears for you.

**Comment by emsal0** [comment]
@wg030 The minimal example is any document with `\usepackage{jlcode}` and any julia code block with minimal text `a`, I believe. 

```
\documentclass{article}
\usepackage{jlcode}
\begin{document}

\begin{lstlisting}[language=Julia]
a
\end{lstlisting}

\end{document}
```

**Comment by wg030** [comment]
@emsal1863 I tested your example, and the code compiled for me successfully.
I also retested my own manual which throw the same error a few days ago, but now it works again.
So it seems as if whatever causes this error outside the jlcode package has been fixed and now everything is fine again.

**Comment by kellertuer** [comment]
I also get a lot of `undefined color: jlbase` independent of whether I set colors to true or false. What might be a reason for that? I really would like to use this package.

When I manually call `\loadcolors`it seems to work. When setting usecolors oto false I would never expect that, but also a use color set to true should load the colors itself?

**Comment by wg030** [comment]
> When I manually call \loadcolors it seems to work. When setting usecolors oto false I would never expect that, but also a use color set to true should load the colors itself?

Well, although using `nocolors=true` has the effect of displaying the code with no colors, the package internally also defines the colors for efficiency reasons. So it makes sense that when you explicittly call `\loadcolors` you get an effect.
However as you said this should not be necessary at all and actually apart from the few strange and yet unexplainable situations reported in this issue, everything works as expected.

But I am already working on the next update which I will release this week, maybe already tomorrow. Insetead of the color and box options all colouring in the code will be rearanged and we will then have a `theme` option. If we are lucky, this will finally solve this strange issue.
Maybe you could report your experience here when the new version of jlcode is released.

**Comment by kellertuer** [comment]
Cool, I will wait for that and happily act as a tester there.

**Comment by wg030** [comment]
@kellertuer
Thanks for you offer to help!
I have just uploaded the new update. Hopefully it will work without this issue. I am waiting for your report.

**Comment by kellertuer** [comment]
Hm, now I get
```
Package jlcode: Option `usebox' is given too late,
(jlcode)	now the option is ignored.
```
and If I comment that option out
```
Package jlcode: Option `usecolors' is given too late,
(jlcode)	now the option is ignored.
```

Is there something I have to keep in mind with the order of loading this?

**Comment by wg030** [comment]
My bad! I should have told you that I jhave removed all these box and color options completley in favour of a new theme option.
So to get the combination of colors and box you want you need to pick out the correct theme and then load the package with `\usepackage[theme=dfltthemenobox]{jlcode}` for a colored code with no box for example. Look at the manual to get an overview of all the themes!

**Comment by kellertuer** [comment]
Ah, sorry, I did not expect so many changes. When we are at it – why did you choose the name `dfltthemebox` especially the `dlft` upfront? hard to read, hard to distinguish, also for the `courierasttdflt`?

**Comment by wg030** [comment]
Well, to be honest I am not maximal happy with these names, but I don't think that they are awfully bad either.
The prefix `dflt` is of course a more or lesse common abbreviation of `default` and I simply did not want to make these names to long like `courierasdefaulttypewritefont` for example.
Maybe I will spend more time to think of better names in the next update.
In my opinion the more crucial point here is whether or not introducing the themes could make the problems with the colors vanish or not.

**Comment by kellertuer** [comment]
ok, sorry that's off-topic, I will propose something in a different issue, since this now here seems to be resolved.

**Comment by wg030** [comment]
Ok, great! If you can confirm that the issue does not appear for you anymore I think I can confidently close this issue and discuss the names with you in the new one!
