### ISSUE TITLE
Unicode box characters for `CodeInfo`

### ISSUE THREAD

**Issue by phipsgabler** [wg030/jlcode#25]
This might be a useful addition for anyone working with Julia internals.

The following definitions, together with [`pmboxdraw`](https://www.sys.kth.se/docs/texlive/texmf-dist/doc/latex/oberdiek/pmboxdraw.pdf), enable typesetting `CodeInfo` print-outs:

```latex
{┌}{{\ucc{\textSFi}}}{1}
{│}{{\ucc{\textSFxi}}}{1}
{└}{{\ucc{\textSFii}}}{1}
{─}{{\ucc{\textSFx}}}{1}
{┄}{{\ucc{\textSFx}}}{1}
```

(The [triple dash horizontal](https://unicode-table.com/en/2504/) character is not available in `pmboxdraw`, but can be replaced by the solid one without confusion, IMO.)

Test case:

```
1 ── %1  = Base.arraysize(x, 1)::Int64
│    %2  = Base.slt_int(%1, 0)::Bool
│    %3  = Base.ifelse(%2, 0, %1)::Int64
│    %4  = Base.slt_int(%3, 1)::Bool
└───       goto #3 if not %4
2 ──       goto #4
3 ──       goto #4
4 ┄─ %8  = φ (#2 => true, #3 => false)::Bool
│    %9  = φ (#3 => 1)::Int64
│    %10 = φ (#3 => 1)::Int64
│    %11 = Base.not_int(%8)::Bool
└───       goto #22 if not %11
```

I'd rather typeset those listings without colors, though, since the highlighter obviously gets confused by internal names.

**Comment by wg030** [comment]
Great suggestion!
I will add this with the next update.

**Comment by wg030** [comment]
I implemented your solution, exactly as suggested, with the latest update!
