### ISSUE TITLE
Incorrect highlighting of var-strings

### ISSUE THREAD

**Issue by phipsgabler** [wg030/jlcode#26]
```julia
var"#sprint#339"
```

In this example, only the part `r"#sprint#339"` is highlighted in red (probably confused with a regex literal).  It should cover the whole `var`, though.

(See https://github.com/JuliaLang/julia/pull/32408.)

**Comment by wg030** [comment]
Hmm, quite strange that my [https://github.com/wg030/jlcode/blob/master/createlists.jl](url) does not recognize this string prefix. I will have to check this out, I guess.
The quickfix is to add the line `morestring=[s]{var"}{"},%` after line 370.

**Comment by phipsgabler** [comment]
It's a builtin of the parser, not a real string macro.  Otherwise expressions like

```
var" x " = y.var" z "
```

couldn't work.  Also, it's not really a string -- ideally, it should belong to the same class as identifiers.

But thanks for the workaround!

**Comment by wg030** [comment]
Ok, I see.
But which way would you prefer to display such expressions then? I am little unsure here.
Should they be displayed like strings, i.e. in red, or would it maybe even better to display them as identifiers, i.e. in black?

**Comment by phipsgabler** [comment]
Definitely like identifiers, I'd say.

**Comment by wg030** [comment]
While updating the package I looked at this issue again.
I decided to go with the solution I already suggested to you because form a sourcecode point of you these expressions are rather strings altough from a programming point of view they are identifiers.
