### ISSUE TITLE
Please do not change the typewriter font

### ISSUE THREAD

**Issue by dpo** [wg030/jlcode#3]
Many thanks for this package, which fills an important gap!

However, I don't think it is this package's job to `\RequirePackage{courier}` and change the typewriter font. I would suggest
```diff
diff --git a/jlcode.sty b/jlcode.sty
index afcaaab..c351434 100644
--- a/jlcode.sty
+++ b/jlcode.sty
@@ -28,7 +28,6 @@
   \RequirePackage{textcomp}%
 \fi
 \RequirePackage{calc}
-\RequirePackage{courier}
 ```

**Comment by wg030** [comment]
Great objection!
I guess your are right, this package should not change the typewriter font.
With the latest version that I have just uploaded I have removed that line and edited/added some others accrodingly because the creation of the code box did only work with courier with the old code.

**Comment by dpo** [comment]
Thank you! I feel somewhat similarly about the default settings and code box. Is it really the job of a language definition package to set those? If a user used `lstset` before `\usepackage{jlcode}`, their settings may be undone.

**Comment by wg030** [comment]
Well, actually this package is not only considered to be a language definition, but rather a package that makes it possible to print code similar to the code snippets of the official julia documentation.
If it was a pure language definition, it would not even make sense to choose the colors or decide in which way keywords are emphasized.
However I might consider to add one or even a few parameters to make this optional in a next release. I will keep your suggestion in mind anyway.

**Comment by dpo** [comment]
I agree. The two (syntax and style) should be separated somehow. Thanks.
