### ISSUE TITLE
Refactor a few keywords in theme

### ISSUE THREAD

**Issue by kellertuer** [wg030/jlcode#30]
Some of the keywords seem to be hard to read and duplicates information.
For the theme there is `theme=dflttheme` which doubles theme. What about `theme=default`? Far better to read and to type.
Similarly
* `theme=dfltthemenobox` what is obox? Since that appears again, would it be reasonable to (again) introduce a `codebox=true|false`?
* `theme=bnwtheme` could be `theme=blackandwhite`? Again the main information of the theme is then not abbreviated
* `theme=bnwthemenobox` see above 
* similarly `theme=darktheme`could just be `theme=dark`

**Comment by wg030** [comment]
The `theme=default`, `theme=blackandwhite` and `theme=dark` sound like good ideas.
With the box I tend to avoid an option like `codebox=true` because I want to make the box styles part of the theme.
For example I would not want to have `theme=dark` and `codebox=false` at the same time because I would not make any sense.
Moreover even `theme=dfltthemenobox` and `theme=bnwthemenobox` actually have a box, it's just an invisible one. So the apperance with the colors and the box kind of belong together for me.

**Comment by kellertuer** [comment]
I see. And `obox` means with box? maybe call these themes then `default-box` and `blackandwhite-box`?

**Comment by wg030** [comment]
:D `theme=dfltthemenobox` is actually intented to be `theme=dflt theme nobox` without the spaces.
`default-box` sounds good, but then again this theme is what I want to have as the real default, so default colors with a box, which would mean that `theme=default` would stand for default colors without a box, which is not supposed to be the default.
And `default-nobox` and especially the analogus `blackandwhite-nobox` wold be a little long, wouldn't it?

**Comment by kellertuer** [comment]
Ah, I missed the `n` from `nobox`; one could go for `default-plain` to describe the not-with-boxes in a positive instead of with a negative feature? `blackandwhite-plain` would also be a little long, but its the noncolor idea? Why not `grayscale` and `grayscale-plain` then?

**Comment by wg030** [comment]
`grayscale` is quite a good idea. But `plain` actually consists as many letters as `nobox` not really making it better.
So what about `default`, `default-nobox`, `grayscale`, `grayscale-nobox` and `dark`, they are all not too long but expressive.

**Comment by kellertuer** [comment]
Well, it's your code. I would not use `-nobox`, because with a negative you can easily get into stacking `nobox-noX-noY`, but sure they are short and well describing, for sure.

**Comment by wg030** [comment]
The possible stacking is a good argument. I think I will need to take my time later and consider what might happen with the package in the future and if stacking could be a possible problem at all.
But I guess I should update the package today anyway before anybody gets used to those other names.

**Comment by wg030** [comment]
Ok, I have now uploaded the package!
I went for you suggestion expect for `dark` which I know called `darkbeamer` because I feel their might be some more dark themes in the future!
Thanks for your help with the naming!

**Comment by kellertuer** [comment]
Cool, though I am not sure why you choose `beamer`; sure.
