### ISSUE TITLE
color of line numbers

### ISSUE THREAD

**Issue by RainerHeintzmann** [wg030/jlcode#36]
I think the color of the line numbers is unfortunately tied to the color of the strings.
It seems to ignore statements like `definecolor{jllinenumbers}{HTML}{000000}%  % the line numbers of the code block`
in the color scheme.
Can one introduce a separate color scheme for line numbers?

**Comment by wg030** [comment]
Well, my intention is to make the line numbers a separate option anyway with the next update.
For now, simply add something like `numbers=left, stepnumber=1, numberstyle=\ttfamily\color{jllinenumbers},` into the definition of `jlcodeboxdfltstyle` in line 509 and/or into the definition of `jlcodeboxnostyle` in line 531.

**Comment by RainerHeintzmann** [comment]
Great! Thanks!

**Comment by wg030** [comment]
As promised there is now the `linenumbers` option!

Using `\usepackage[linenumbers=true]{jlcode}` will activate them which means that you can now change the color sheme the way you originally intented!

**Comment by RainerHeintzmann** [comment]
Great! Thanks!
