### ISSUE TITLE
Complex{Int64} problem

### ISSUE THREAD

**Issue by RainerHeintzmann** [wg030/jlcode#37]
`\jlinl{Complex{Int64}}`
gives a destroyed output:
`nt64ComplexI`
Can this be fixed?

**Comment by RainerHeintzmann** [comment]
If the inner bracket is protected, it works: `\jlinl{Complex\{Int64\}}`.

**Comment by wg030** [comment]
Yes, that's a known problem that also applies to the characters `%` and `\`, which cause some kind of trouble if not decoded as `\%` and `\\`, too.
Since this is already explained in the manual I will close this issue!
