### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by qiyuan-zheng** [wg030/jlcode#39]
Errors include:

jlcode.sty:59: Undefined control sequence. [\iftutex]
jlcode.sty:61: Extra \else. [\else]
jlcode.sty:68: Extra \fi. [\fi]

and a lot more

**Comment by wg030** [comment]
Hi @qiyuan-zheng!
That should not happen, of course. There seems to be something wrong with the `iftex` package here because the errors all point to commands that belong to this package.
Are you sure you have the package installed? If so, maybe you need to update your MikTeX distruibution?!
