### ISSUE TITLE
Customize code block length

### ISSUE THREAD

**Issue by ErikQQY** [wg030/jlcode#40]
First of all, thanks a lot for your contributions! It helped me a lot😆

I think customizing code block length maybe better for users, so users can set the size of code block according to their requirements?

**Comment by wg030** [comment]
Hi @ErikQQY!

> First of all, thanks a lot for your contributions! It helped me a lot😆

That's nice to hear! 😀



> I think customizing code block length maybe better for users, so users can set the size of code block according to their requirements?

I am not quite sure what you really mean by this. But technically the user can set the width of the code box using the `charsperline` package option (compare the manual). This should make it possible to modify the code block as desired or do you need something that cannot be done with that option?

**Comment by ErikQQY** [comment]
@wg030 Thanks a lot for your quick and useful response

I am using ```multicols``` in my paper, by setting ```charsperline=50``` help me modify the code block width

```latex
\usepackage[charsperline=50]{jicode}
```
![original](https://user-images.githubusercontent.com/52615090/149457927-b807f500-b623-4b84-90d5-d9c0ff52de8a.png)

After modifying:

![later](https://user-images.githubusercontent.com/52615090/149457965-8de5e22c-fb0d-4a90-a061-e4784a049da5.png)
