### ISSUE TITLE
Color of functions containing "!"

### ISSUE THREAD

**Issue by GiannisTsagkaropoulos** [wg030/jlcode#42]
Functions such as "append!" are not coloured with the "jlfunctions" colour. The text, before the "!" is instead coloured with the "jlbase" colour and the exclamation mark is coloured with the "jlop" colour .

**Comment by wg030** [comment]
Well, that's indeed a bug. Thanks for reporting.
I think I can fix it in the next version by literating all those functions separtetly.

For now, you can quickfix all your functions with `!` in your code manually:
Put the following lines of code to `jlcode.sty` at `line 2047`:
```latex
\newcommand{\addlitjlfunctions}[3]{%
\lstset{style=jlcodeuccstyle}
\lstdefinestyle{jlcodeuccstyle}{expandliterate={#1}{{{\color{jlfunctions}#2}}}{#3}}
\ifjlc@autoload
  \lstset{language=julia, style=jlcodestyle}
\fi
}
```
Then add for each function a line like the following to the preample of your latex document after `\usepackage{jlcode}`:
```latex
\addlitjlfunctions{append!}{append!}{7}
```

**Comment by GiannisTsagkaropoulos** [comment]
Works like magic! Thanks a lot

**Comment by wg030** [comment]
> Works like magic! Thanks a lot

Your are welcome!
However I would like to leave that issue open until I will really fix it for everybody with the next update.

**Comment by wg030** [comment]
With the latest update to version 6.1 I know added the command `\addlitjlfunctions` so that self defined functions ending with `!` can now be manually fixed. Moreover I made sure that all standard functions ending with `!` are now displayed correctly.
Thanks again for reporting that issue.
