### ISSUE TITLE
Line breaking is bad

### ISSUE THREAD

**Issue by KronosTheLate** [wg030/jlcode#43]
Loving this package.

I am having some issues with ugly linebreaks:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/61620837/163784869-1510a111-c97d-479e-823a-4ff4586590ef.png">

The lines break at a point, just not soon enough. This makes me feel like the problem could be fixed.

**Comment by wg030** [comment]
> Loving this package.

Thanks you very much.


> I am having some issues with ugly linebreaks:

😁 That looks indeed very ugly, not quite sure what could be happening here yet. It might be fixable with the `charsperline` option. Did you try that, maybe this is already sufficient.
Otherwise, could you post some code so that I can reproduce the output?

**Comment by KronosTheLate** [comment]
```
\begin{jllisting}
this is any old line inside a jllisting that is too long. It seems like the grey bounding box is smaller than the limits of the textwidth.
\end{jllisting}
```

produces
<img width="619" alt="image" src="https://user-images.githubusercontent.com/61620837/163789974-14e90de8-645d-41e3-9ae5-1c109ae9ce83.png">

to me.

Trying to add `charsperline` gives an error, and no improvement:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/61620837/163790160-8b300b69-052e-42ef-89c8-6f49cd95cc96.png">

**Comment by wg030** [comment]
> Trying to add `charsperline` gives an error, and no improvement:

`charsperline` is a direct package option with a default value of 80.
So try something like `\usepackage[charsperline=100]{jlcode}` to increase the width of the code box.

**Comment by KronosTheLate** [comment]
`\usepackage[charsperline=60]{jlcode}` produces
<img width="557" alt="image" src="https://user-images.githubusercontent.com/61620837/163792382-d8fcdeb3-2339-40a2-9141-ab1f90394eda.png">.

So it changes the gray box, but not the line-breaking.

Setting it to 100 does produces the following:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/61620837/163792592-58a056c9-8348-4b34-9145-a17e2f53d40d.png">

**Comment by wg030** [comment]
Well, most programmers fromat their code such that they never go beyond a maximum number of characters per line and add breaks in their code accordinglty. I usually take 80 as maximum value, but others might go for 100 or even more. I that case you simply use `charsperline` and everyhting should work as desired.

However, if you wanna display code that has extremely long (non-broken) lines and you want them to be broken by latex, you would make use of breaklines=true option like this:

```
\begin{jllisting}[breaklines=true]
this is any old line inside a jllisting that is too long. It seems like the grey bounding box is smaller than the limits of the textwidth.
\end{jllisting}
```
This produces the right output. Hopefully, it will work for your original example, too.

**Comment by KronosTheLate** [comment]
Right. I have not yet gotten used to automatic line breaking, so perhaps that is on me.
If most programmers have no more than 80 chars per line, they will not have this problem. But those of us who down, will have this problem.
It seems to me as if setting breaklines to true would help people like me, and not be noticeable by people who limit their chars per line. Would you consider making breaklines=true the default?

EDIT: in fact, breaklines=true only effects the case which produces output like in the OP. This is never desirable, right? A misplaced linebreak will always be better, as far as I can tell.

**Comment by wg030** [comment]
> It seems to me as if setting breaklines to true would help people like me, and not be noticeable by people who limit their chars per line. Would you consider making breaklines=true the default?
> 
> EDIT: in fact, breaklines=true only effects the case which produces output like in the OP. This is never desirable, right? A misplaced linebreak will always be better, as far as I can tell.

I will check this out for the next update, but yes, it looks like as if it makes quite a lot sense to set this as the default option since it seems that this optione has no effect when all lines are short.

**Comment by wg030** [comment]
> in fact, breaklines=true only effects the case which produces output like in the OP.

My testing confirmed that this statement is indeed true.
Hence I added that to the package by default, which means one can from now on simply write
```latex
\begin{jllisting}
this is any old line inside a jllisting that is too long. It seems like the grey bounding box is smaller than the limits of the textwidth.
\end{jllisting}
```
and everything should be fine.
