### ISSUE TITLE
Highlighting of macros

### ISSUE THREAD

**Issue by blegat** [wg030/jlcode#44]
Would it be possible to highlight macros as well ?

**Comment by wg030** [comment]
Hi!
What exactly do you mean? We already have the names of all standard macros like `@time` highlighted. Do you refer to the names of self defined macros or what would you like to be highlighted, too?

**Comment by blegat** [comment]
I mean the names of self-define macros. For example, this line:
https://github.com/jump-dev/MutableArithmetics.jl/blob/bcafec7bc6ff0079fa26e9f9bed34590859ae94f/paper/paper.tex#L340
I see that the `@time` macro already works.

**Comment by wg030** [comment]
Well, this can be done, but it needs to be done manually:
Put the following lines of code to `jlcode.sty` at `line 2047`:

```latex
\newcommand{\addlitjlmacros}[3]{%
\lstset{style=jlcodeuccstyle}
\lstdefinestyle{jlcodeuccstyle}{expandliterate={#1}{{{\color{jlmacros}#2}}}{#3}}
\ifjlc@autoload
  \lstset{language=julia, style=jlcodestyle}
\fi
}
```
Then add for each self-defined macro a line like the following to the preample of your latex document after `\usepackage{jlcode}`:
```latex
\addlitjlmacros{@rewrite}{@rewrite}{8}
```

**Comment by wg030** [comment]
I added the `\addlitjlmacros` command to the package now so that one can now fix that problem manually.
I also updated the manual to demonstrate how this is done.
Thanks for reporting this issue.
