### ISSUE TITLE
xelatex, lualatex

### ISSUE THREAD

**Issue by togo59** [wg030/jlcode#5]
Minor issue: Works brilliantly for pdflatex but not xelatex or lualatex unless I'm doing something wrong. The last two omit subscripts and Greek symbols.

**Comment by wg030** [comment]
I have personally never used xelatex or lualatex so I cannot really help you out with this issue.
But it sounds as if unicode characters might be treated differently here.

If somebody else, who knows what is going on when using xelatex or lualatex, told us here, it would be highly aprreciated.

**Comment by togo59** [comment]
OK. I'll just stick to pdflatex. :)
