### ISSUE TITLE
REPL format: Colorize `julia>` if any 

### ISSUE THREAD

**Issue by filchristou** [wg030/jlcode#53]
I think it would be a nice addition to colorize the `julia>` string if any. 
More or less as it's already default by Documenter.jl
A random example: https://dataframes.juliadata.org/stable/man/getting_started/#The-DataFrame-Type

**Comment by wg030** [comment]
> I think it would be a nice addition to colorize the `julia>` string if any.

Well, why not?!
I mean there is the little drawback that if someone codes a programm that uses a variable named `julia` and compares that with a greater realation `>` and does not use space in his code, he will have an ugly output.
But who codes shitty code like this anway?
```julia
julia=42
if julia>Inf
println("I knew it!")
end
```
Right? And even if somebody would want to have such code for whatever strange reason they can sill manually fix the problem as explained in the manual.

I have just uploaded a small little change to the package such that the code 
```latex
\documentclass[11pt,a4paper]{article}

\usepackage[theme=default]{jlcode}
\begin{document}

\begin{jllisting}
julia> using DataFrames Int

julia> DataFrame(a=1:4, b=["M", "F", "F", "M"]) # keyword argument constructor
\end{jllisting}

\end{document}
```
should give the output that you suggested!

**Comment by filchristou** [comment]
awesome ! thanks a million !
