### ISSUE TITLE
"in" symbol

### ISSUE THREAD

**Issue by dpo** [wg030/jlcode#6]
What's the right place to add
```
{∈}{{$\in$}}{1}
```
Thanks.

**Comment by wg030** [comment]
Hey dpo,
I hope you have found the right place to add your ∈ symbol!
I have added that symbol with the last modification that I have just uploaded anyway. Hence I consider you issues to be solved!
I also added a new line to the example code demonstrating this symbol!
Regards

**Comment by dpo** [comment]
Thank you!
