### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by Ashymad** [wg030/jlcode#8]
Unless you specify a license for your code, it is considered proprietary. Usually for LaTeX packages the [LPPL](https://www.latex-project.org/lppl/) is used.

**Comment by wg030** [comment]
Thanks for your hint, @Ashymad !
With the latest changes and additions I have just uploaded, I also added a LPPL hint as you suggested.
Maybe you can check out if I did that in the correct way!

**Comment by Ashymad** [comment]
Great! Thank you very much :)
